containers:
  - name: master
    image: my-mr:0.1
    imagePullPolicy: IfNotPresent
    env:
      - name: MR_LISTEN_ADDR
        value: "0.0.0.0:1234"
    ports:
      - containerPort: 1234
    args: ["/data/sample.pdf", "/data/sample2.pdf"]
    volumeMounts:
      - name: data
        mountPath: /data

