apiVersion: batch/v1
kind: Job
metadata:
  name: mr-worker
  namespace: mr
spec:
  template:
    spec:
      containers:
        - name: worker
          image: my-mr:0.4
          imagePullPolicy: IfNotPresent
          command: ["/app/mrworker"]
          args: ["/app/llm.so"]
          workingDir: /data
          env:
            - name: MR_COORD_ENDPOINT
              value: "mr-master:1234"
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: openai-secret
                  key: OPENAI_API_KEY
          volumeMounts:
            - name: data
              mountPath: /data
      restartPolicy: OnFailure
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: mr-data
  parallelism: 10
  completions: 10
  backoffLimit: 4
